using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using RecluseEdit.Sdk.Models;
using RecluseEdit.Sdk.Providers;

namespace RecluseEdit.Extensions.Scripting.Providers;

/// <summary>
/// Provides inline ghost-text completions and snippets for Bash and POSIX Shell,
/// including shebang, strict mode, conditionals, loops, heredocs, and error trapping.
/// </summary>
public class BashCompletionProvider : IInlineCompletionProvider
{
    public string Id => "bash.core.completion";
    public string Name => "Bash Core Idioms & Snippets";
    public IReadOnlyList<string> SupportedLanguages => ["bash"];

    private static readonly Dictionary<string, string> Completions = new(StringComparer.Ordinal)
    {
        { "#!/", "usr/bin/env bash\nset -euo pipefail\nIFS=$'\\n\\t'\n\nSCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" &amp;&amp; pwd)\"\n" },
        { "function ", "main() {\n\tlocal name=\"${1:-world}\"\n\techo \"Hello, ${name}!\"\n}\n\nmain \"$@\"" },
        { "if [[ -f ", "\"$file\" ]]; then\n\techo \"File exists: $file\"\nelse\n\techo \"File missing: $file\" >&amp;2\n\texit 1\nfi" },
        { "if [[ -z ", "\"${1:-}\" ]]; then\n\techo \"Usage: $0 &lt;argument&gt;\" >&amp;2\n\texit 1\nfi" },
        { "for item in ", "\"${items[@]}\"; do\n\techo \"Processing: $item\"\ndone" },
        { "while IFS= read -r ", "line; do\n\techo \"$line\"\ndone &lt; \"$input_file\"" },
        { "case \"$", "1\" in\n\tstart)\n\t\techo \"Starting service...\"\n\t\t;;\n\tstop)\n\t\techo \"Stopping service...\"\n\t\t;;\n\trestart)\n\t\techo \"Restarting service...\"\n\t\t;;\n\t*)\n\t\techo \"Usage: $0 {start|stop|restart}\" >&amp;2\n\t\texit 1\n\t\t;;\nesac" },
        { "trap '", "echo \"[ERROR] Failed on line $LINENO\"' ERR" },
        { "cat &lt;&lt; 'EOF' > ", "output.txt\n# Configuration file generated by script\nEOF" }
    };

    public Task<string?> GetInlineSuggestionAsync(InlineCompletionContext context, CancellationToken cancellationToken = default)
    {
        var line = context.CurrentLineText.TrimStart();

        foreach (var (prefix, suggestion) in Completions)
        {
            if (line.EndsWith(prefix, StringComparison.Ordinal))
            {
                return Task.FromResult<string?>(suggestion);
            }
        }

        return Task.FromResult<string?>(null);
    }
}
