<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RecluseEdit.Sdk\RecluseEdit.Sdk.csproj" />
    <ProjectReference Include="..\..\RecluseEdit.csproj" />
    <ProjectReference Include="..\..\extensions\RecluseEdit.Extensions.React\RecluseEdit.Extensions.React.csproj" />
    <ProjectReference Include="..\..\extensions\RecluseEdit.Extensions.Angular\RecluseEdit.Extensions.Angular.csproj" />
    <ProjectReference Include="..\..\extensions\RecluseEdit.Extensions.Flutter\RecluseEdit.Extensions.Flutter.csproj" />
    <ProjectReference Include="..\..\extensions\RecluseEdit.Extensions.Php\RecluseEdit.Extensions.Php.csproj" />
  </ItemGroup>

</Project>
